# Generated by Django 5.0.4 on 2024-04-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('image', models.URLField()),
                ('data', models.JSONField()),
                ('favorite_station', models.JSONField()),
            ],
        ),
    ]
