# Generated by Django 5.0.4 on 2024-04-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_userdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='stationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station', models.CharField(max_length=100)),
                ('image', models.URLField()),
            ],
        ),
    ]
